name: Exostia
version: 1.0.3
author: Nistro
description: Main plugin for Exostia server.
main: fr.nistro.exostia.Main
api: INVALID
depend: [Vault, PlaceholderAPI]

commands:
  chat:
    description: Manage chat by clearing it or toggling it.
    usage: /chat <clear|toggle>
    aliases: [c]
    permission: exostia.chat
  welcome:
    description: Welcome player and get a reward.
    usage: /welcome
    aliases: [b, bienvenue, bvn]
    